audio:
  input_device: Logi USB Headset      # index or name substring; use scripts/list_devices.py
  output_device: Logi USB Headset     # index or name substring
  sample_rate: 16000
  chunk_ms: 30

wake:
  backend: "porcupine"     # "keyboard" | "porcupine" | "openwakeword"
  porcupine:
    # Use EITHER 'keyword' for built-ins OR 'ppn_path' for your custom .ppn
    #keyword: "jarvis"     # built-in keywords require AccessKey
    ppn_path: models/porcupine/Ophelia.ppn         # e.g., "models/porcupine/Ophelia.ppn"
    sensitivity: 0.6       # 0.0..1.0 (higher = more sensitive)
    access_key_env: "PORCUPINE_ACCESS_KEY"
  openwakeword:
    model_path: "models/openwakeword/hey_jarvis.tflite"  # placeholder


asr:
  backend: "faster_whisper"   # or "sherpa"
  faster_whisper:
    model_id: "Systran/faster-whisper-tiny.en"  # light model to start
    compute_type: "int8"                         # Jetson-friendly
  sherpa:
    model_dir: "models/sherpa_whisper_tiny_en"   # placeholder

llm:
  model_path: "models/qwen2-0.5b/qwen2-0.5b-instruct-q8_0.gguf"  # small GGUF
  n_ctx: 2048
  n_gpu_layers: -1

tts:
  backend: "piper"  # only piper in this skeleton
  piper:
    voice_path: "models/piper/en_US-lessac-high.onnx"  # example voice
    output_wav: "out.wav"